print("\nWelcome to the  Game !!!!!!!!!!!!!")
print("**********************************")
input()
print("Please Follow the Instructions Given Below :")
print("*******************************************\n")
input()
print("You are Advised to Think of a Number Between 3 and 3  And  Answer for the further Questions:")
print("********************************************************************************************\n")
input()
print("Is the Number is 3 ? \n")
print("Tell Yes or No\n")
input()
print("\nThe Number You Thought was 3 And I Won the Game :)\n")
